# Generated by Django 3.0.8 on 2020-12-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itjob', '0003_auto_20201216_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='published_date',
            field=models.DateField(),
        ),
    ]
