# Generated by Django 3.0.8 on 2020-12-20 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itjob', '0005_remove_vacancy_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='apply_before',
        ),
    ]
