# Generated by Django 3.0.8 on 2020-12-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itjob', '0011_auto_20201221_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='apply_before',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='education',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='requirements',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
