# Generated by Django 3.0.8 on 2020-12-16 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itjob', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='company_pics'),
        ),
    ]
