# Generated by Django 3.0.8 on 2020-12-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itjob', '0007_auto_20201220_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='req_no',
            field=models.IntegerField(default=1),
        ),
    ]
