# Generated by Django 3.0.8 on 2020-12-21 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itjob', '0008_auto_20201220_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='req_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
