# Generated by Django 3.0.8 on 2020-12-21 10:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('itjob', '0010_auto_20201221_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='apply_before',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='req_no',
            field=models.IntegerField(default=1),
        ),
    ]
