# Generated by Django 3.0.8 on 2020-12-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itjob', '0012_auto_20201221_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='req_no',
            field=models.IntegerField(null=True),
        ),
    ]
