# Generated by Django 3.0.8 on 2020-12-23 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itjob', '0013_auto_20201221_1825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'get_latest_by': ['-published_date']},
        ),
    ]
